import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name : 'Kosaku Tsubata',
      email: "kosaku@gmail.com",
      password: bcrypt.hashSync("kosaku"),
      isAdmin: true
    },
    {
      name : 'Misaki',
      email: "misaki@gmail.com",
      password: bcrypt.hashSync("misaki"),
      isAdmin: false
    }
],
  products: [
    {
      name: 'バッティングセンターにいく',
      slug: 'battling-center-to-go',
      category: 'sports',
      image: '/images/batting.jpg',
      price: 1000,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒にバッティングセンターにいく。小学校４年生から6年生までやっていたのでちょっとはできるはず。かっこいいと思ってもらえると嬉しい。',
    },
    {
      name: '温泉旅行に行く',
      slug: 'go-to-a-spa',
      category: 'relaxation',
      image: '/images/spa.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: '温泉旅行に行く。近場でも遠くでも。夜はしっぽり語る。',
    },
    {
      name: '家で料理を振る舞う',
      slug: 'cook-at-home',
      category: 'relaxation',
      image: '/images/cooking.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '料理を振る舞って日頃の労いをしたい。',
    },
    {
      name: '陶芸にチャレンジする',
      slug: 'challenge-to-craft',
      category: 'Pants',
      image: '/images/craft.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '個人的にずっとやってみたかった。お揃いのものとか作れたらとてもほっこりしそう。',
    },
    {
      name: 'BBQする',
      slug: 'bbq',
      category: 'outdoor',
      image: '/images/camp.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'クラシックの演奏会に行く',
      slug: 'go-to-a-concert',
      category: 'hobby',
      image: '/images/classic.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'クラシックの演奏会に行く。クラシックの中でもキャッチーで楽しめそうなやつとかチョイスしたい。感想も気になる。',
    },
  ],
};
export default data;