import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name : 'Kosaku Tsubata',
      email: "kosaku@gmail.com",
      password: bcrypt.hashSync("kosaku"),
      isAdmin: true
    },
    {
      name : 'Misaki',
      email: "misaki@gmail.com",
      password: bcrypt.hashSync("misaki"),
      isAdmin: false
    }
],
  products: [
    {
      name: 'バッティングセンターにいく',
      slug: 'battling-center-to-go',
      category: 'アクティビティ',
      image: '/images/batting.jpg',
      price: 1000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒にバッティングセンターにいく。小学校の頃やってました。普段やらないから楽しそう。',
    },
    {
      name: '温泉旅行に行く',
      slug: 'go-to-a-spa',
      category: 'リラクゼーション',
      image: '/images/spa2.jpg',
      price: 50000,
      brand: '短期',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: '温泉旅行に行く。近場でも遠くでも。夜はしっぽり語る。',
    },
    {
      name: '家で料理を振る舞う',
      slug: 'cook-at-home',
      category: 'リラクゼーション',
      image: '/images/cooking.jpg',
      price: 2000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '料理を振る舞って日頃の労いをしたい。好きな味を提供したい。',
    },
    {
      name: '陶芸にチャレンジする',
      slug: 'challenge-to-craft',
      category: 'アクティビティ',
      image: '/images/craft.jpg',
      price: 5000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '個人的にずっとやってみたかった。お揃いのものとか作れたらとてもほっこりしそう。作品がずっと残るのもエモい。',
    },
    {
      name: '二人キャンプする',
      slug: 'camp',
      category: 'アウトドア',
      image: '/images/camp.jpg',
      price: 10000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '二人でキャンプに行く。星を見たい。焚き火したい。将来の話とかしたい。',
    },
    {
      name: '水族館にいく',
      slug: 'aquarium',
      category: 'アウトドア',
      image: '/images/aquarium.png',
      price: 10000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '定番。僕の水族館の楽しみ方いつも変て言われるから反応が気になる。',
    },
    {
      name: '映画を見る',
      slug: 'watch-movie',
      category: 'アクティビティ',
      image: '/images/movie.png',
      price: 5000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'いろいろな映画を見て感想を聞きたい。',
    },
    {
      name: '将来設計を考える',
      slug: 'future',
      category: 'アウトドア',
      image: '/images/future.png',
      price: 0,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '今後の話をする。',
    },
    {
      name: '誕生日を祝う',
      slug: 'birthday',
      category: 'アウトドア',
      image: '/images/birthday.png',
      price: 0,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '誕生日を祝ってあげたい。ない頭を使って何か企画する。',
    },
    {
      name: 'ジョギング',
      slug: 'jogging',
      category: 'アウトドア',
      image: '/images/jogging.png',
      price: 0,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '暖かくなったら健康を意識して一緒にジョギングしたい。',
    },
    {
      name: '花見に行く',
      slug: 'hanami',
      category: 'アウトドア',
      image: '/images/hanami.png',
      price: 0,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '桜を見ながらお酒を飲む。春の醍醐味。',
    },
    {
      name: 'BBQ',
      slug: 'bbq',
      category: 'アウトドア',
      image: '/images/bbq.jpg',
      price: 10000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'BBQする。外で食べるの好き。お互いの友達を誘って集まるのとかもいつかやってみたい。',
    },
    {
      name: '友達に紹介する',
      slug: 'introduce-to-friends',
      category: '付き合い',
      image: '/images/friend.png',
      price: 5000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '友人に会ってもらって僕を知ってもらう。大学の同期か前職の友人。',
    },
    {
      name: 'ディベート',
      slug: 'debate',
      category: '付き合い',
      image: '/images/debate.png',
      price: 0,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'みさきは頭が良いのでディベート楽しそう。お互いの思考の癖みたいなのも見えてきそう。',
    },
    {
      name: 'クラシックの演奏会に行く',
      slug: 'go-to-a-concert',
      category: '趣味',
      image: '/images/classic.jpg',
      price: 10000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'クラシックの演奏会に行く。クラシックの中でもキャッチーで楽しめそうなやつとかチョイスしたい。感想も気になる。',
    },
    {
      name: '海に行く',
      slug: 'go-to-the-sea',
      category: 'アウトドア',
      image: '/images/sea.jpg',
      price: 5000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '軽くドライブもよい。夏に海に行くとかカップルっぽいことしたい。',
    },
    {
      name: '花火を見に行く',
      slug: 'fireworks',
      category: 'アウトドア',
      image: '/images/fireworks.png',
      price: 10000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '手を握りながら花火を見るという青春っぽいことをしたい。',
    },
    {
      name: '山登りする',
      slug: 'climb-mountain',
      category: 'アウトドア',
      image: '/images/mountain.png',
      price: 5000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '山の中を一緒に歩きたい。いい景色とか見たい。',
    },
    {
      name: 'ピクニックに行きたい',
      slug: 'picnic',
      category: 'アウトドア',
      image: '/images/picnic.png',
      price: 5000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒にほのぼのしたい。ロカボのサンドイッチ作る。',
    },
    {
      name: '手を繋いで散歩する',
      slug: 'walking',
      category: 'アウトドア',
      image: '/images/walking.png',
      price: 5000,
      brand: '短期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '天気の良い日にほのぼの散歩したい。',
    },
    {
      name: '遊園地にいく',
      slug: 'go-to-a-park',
      category: 'アウトドア',
      image: '/images/park.jpg',
      price: 20000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '遊園地に行く。叫んでみたい',
    },
    {
      name: 'ディズニーリゾート系',
      slug: 'go-to-a-disney-resort',
      category: 'アウトドア',
      image: '/images/disney.jpg',
      price: 20000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'ターキー食べたい。楽しそうな美咲さんをみたい。',
    },
    {
      name: 'めっちゃ飲む',
      slug: 'drink-a-lot',
      category: '遊び',
      image: '/images/vodka.jpg',
      price: 10000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '健康が大事なので一度だけ。一緒に潰れる。やっぱり少し怖い。',
    },
    {
      name: 'ライブに来てもらう',
      slug: 'invite-to-a-live',
      category: '趣味',
      image: '/images/live.png',
      price: 1000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '演奏で楽しませられるかチャレンジしたい。',
    },
    {
      name: '先輩に紹介する',
      slug: 'introduce-to-previous-bosses',
      category: '付き合い',
      image: '/images/boss.png',
      price: 10000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'なんだかんだお世話になっている先輩にも紹介したいかも。先輩たちの元カノにノリで生きている人が多かったからなんだかんだ気が合いそう。',
    },

    {
      name: '海外旅行にいく',
      slug: 'got-to-a-foreign-country',
      category: '旅行',
      image: '/images/foreign.png',
      price: 200000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'いろいろ落ち着いたら行きたい。言葉が通じないところに行きたい。',
    },
    {
      name: 'フェスに行く',
      slug: 'go-to-festival',
      category: 'アウトドア',
      image: '/images/fes.png',
      price: 20000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒に盛り上がってみたい。はしゃいでるところ見たい。',
    },
    {
      name: '国内旅行にいく',
      slug: 'travel-in-japan',
      category: '旅行',
      image: '/images/japan.png',
      price: 50000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'おいしいもの食べてるところをみたい。',
    },
    {
      name: 'カラオケに行く',
      slug: 'karaoke',
      category: '娯楽',
      image: '/images/karaoke.png',
      price: 2000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '歌ってるところ見たい。声可愛いから聞きたい。',
    },
    {
      name: 'テニスをする',
      slug: 'tennis',
      category: '娯楽',
      image: '/images/tennis.png',
      price: 0,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '意外と動けるところを見せたい。',
    },
    {
      name: '劇団四季を見に行く',
      slug: 'shiki',
      category: '趣味',
      image: '/images/shiki.png',
      price: 0,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒に楽しめそう。楽しそうな顔見たい。',
    },
    {
      name: '岩盤浴に行く',
      slug: 'ganban',
      category: 'リラクゼーション',
      image: '/images/ganban.png',
      price: 0,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒に癒される。日頃の疲れをとる。',
    },
    {
      name: '同棲する',
      slug: 'live-together',
      category: '付き合い',
      image: '/images/together.png',
      price: 0,
      brand: '年内？',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '同棲したい。早めに同棲するのが美咲さんにとって良いのではないかと最近考えている。',
    },
    {
      name: '手料理を作ってもらう',
      slug: 'ask-to-cook',
      category: '趣味',
      image: '/images/cook.png',
      price: 2000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '迷惑でなければ食べてみたい。ほっこりしそう。',
    },
    {
      name: 'スキューバダイビングやる',
      slug: 'scuba-diving',
      category: 'アウトドア',
      image: '/images/scuba.png',
      price: 50000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒に楽しめるものもあったら良いかも。楽しんでるところ見たい。',
    },
    {
      name: '世界遺産をめぐる',
      slug: 'world-heritage',
      category: 'アウトドア',
      image: '/images/world-heritage.png',
      price: 1000000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '歴史の勉強とかして世界遺産を見に行きたい。',
    },
    {
      name: '一緒にジムに通う',
      slug: 'jym',
      category: '健康',
      image: '/images/jym.png',
      price: 10000,
      brand: '中期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '健康のために一緒に通ってみたい。',
    },
    {
      name: 'ゴルフする',
      slug: 'go-to-golf',
      category: 'アウトドア',
      image: '/images/golf.png',
      price: 20000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '親戚のおじさんからも誘われているからやることないくらい落ち着いたらやってみたい。',
    },
    {
      name: '一緒に謎のイベントに参加する',
      slug: 'mystery-event',
      category: '娯楽',
      image: '/images/event.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '東京は謎のイベントが多いから一緒に参加してそれについて話してみたい。',
    },
    {
      name: 'ボランティアに参加する',
      slug: 'volunteer',
      category: '娯楽',
      image: '/images/volunteer.png',
      price: 0,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '一緒にボランティアに参加してみたい。知らない一面が見えそう。',
    },
    {
      name: 'スノボーする',
      slug: 'snowboarding',
      category: 'アウトドア',
      image: '/images/snowboarding.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '怪我が嫌だからあまりやりたくはないけど、やってるところ見てみたい。',
    },
    {
      name: '親に紹介する',
      slug: 'introduce-to-parents',
      category: '付き合い',
      image: '/images/parent.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '親に紹介したい。べっぴんさんだねーと言われる。',
    },
    {
      name: '1日中いちゃいちゃする',
      slug: 'lovey-day',
      category: '娯楽',
      image: '/images/parent.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '今は常にいろいろ考えてるからいつか何も考えずにずっといちゃいちゃする日があるのも楽しそう。',
    },
    {
      name: '親御さんに紹介される',
      slug: 'be-introduced-to-parents',
      category: '付き合い',
      image: '/images/mother.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '親御さんに紹介されたい。べっぴんさんだねーと言われたい。',
    },
    {
      name: '地元の友達に紹介する。',
      slug: 'introduce-to-local-friends',
      category: '付き合い',
      image: '/images/friends.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'なんだかんだ地元大事。',
    },
    {
      name: '仕事を手伝ってもらう',
      slug: 'get-help-with-work',
      category: '仕事',
      image: '/images/lady.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'お金を払って仕事を手伝ってもらいたい。美咲さんの好きな仕事とか用意できたらベスト。',
    },
    {
      name: '喧嘩して仲直りする',
      slug: 'fight',
      category: '付き合い',
      image: '/images/fight.png',
      price: 10000,
      brand: '長期',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: '喧嘩しなそうだけど、仲直りしてみたい。',
    },

  ],
};
export default data;